### ISSUE TITLE
BISFixed development tracking

### ISSUE THREAD

**Issue by saintblood** [saintblood/CSGN_ServicePack#1]
- [x] hide future stuff and CSAT Hexcamo
- [x] replace magazines with csgn-magazines where they fit
- [x] change caliber of sdar to 7.62 (like it is in rl)
- [ ] adapt sdars stats to reflect the new caliber (needs testing first)
- [ ] vehicles need to be done - pending unitsaddons for nato
- [ ] dependecy needs to be done (cfgPatches)
- [ ] check translations/names
- [ ] cleanup
