### ISSUE TITLE
CSGN_SP_RH_M4_A3 decelopment tracking

### ISSUE THREAD

**Issue by saintblood** [saintblood/CSGN_ServicePack#10]
- [x] add csgn-magazines
- [ ] create .300 BLK mags and assign them (honey badger)
- [ ] hide unpleasant/duplicate weapons - though again i cant think of anything unpleasant to hide here.. much good
- [ ] cleanup
