### ISSUE TITLE
CSGN_SP_USAF development tracking

### ISSUE THREAD

**Issue by saintblood** [saintblood/CSGN_ServicePack#13]
- [ ] hide unpleasant gear - though it is nice, its a sh**load of stuff cluttering up arsenal
- [x] empty loaded backpacks - the idea of it is good, the system is bad, cluttering up when you respawn or something
- [ ] vehicle whitelisting and update crews for units-addon
- [ ] cleanup
- [ ] translation
