### ISSUE TITLE
CSGN_SP_UnitsUS Stage 1

### ISSUE THREAD

**Issue by saintblood** [saintblood/CSGN_ServicePack#15]
##### Stage one - for the first release

- [x] create pbo structure
- [x] translation
- [x] ~~cleanup~~ moved to global

###### camo style to do:
- [x] mtp

###### classes infanftry:
- [x] ~~unarmed soldier (maybe scratch that one.. have to think)~~
- [x] ~~survivor (maybe scratch that one.. have to think)~~
- [x] rifleman light (no nvg, cap, reduced load)
- [x] rifleman
- [x] rifleman at
- [x] grenadier
- [x] teamleader
- [x] squadleader
- [x] officer ( cpt. fancypants, basicly rifleman light with barett, terminal and rangefinder)
- [x] designated marksman
- [x] light machine gunner (556)
- [x] heavy machine gunner (762)
- [x] medic (maybe split into cfr=acemedic and medic=acedoctor, maybe at a later stage)
- [x] ammo carrier (base version with empty backpack.. maybe specific to those who need him later)
- [x] uav operator (maybe will be moved into another vehicleclass at a later stage)
- [x] aa specialist
- [x] at specialist
- [x] repair specialist
- [x] explosives specialist
- [x] ~~engineer~~

###### classes crewman:
- [x] tankcrew
- [x] helipilot
- [x] helicrew
- [x] pilot
