### ISSUE TITLE
CSGN_SP_BISFixedUnits dev tracking

### ISSUE THREAD

**Issue by saintblood** [saintblood/CSGN_ServicePack#19]
- [ ] blufor units (look steam or __info.txt)
- [x] blufor vehicles
- [ ] redfor units
- [ ] redfor vehicles (maybe we should hide that ugly hexcamo?)
- [ ] indep units
- [ ] indep vehicles
- [x] civ units + vehicles
