### ISSUE TITLE
CSGN_SP_HAFM_A3 development tracking

### ISSUE THREAD

**Issue by saintblood** [saintblood/CSGN_ServicePack#3]
- [x] add csgn-mags to weapons
- [ ] hide units - covered with own addon
- [ ] hide unpleasant/duplicated weapons
- [ ] update vehicles for whitelist and add crew to it (pending CSGN_SP_unitsGRE)
- [ ] check equipment if stuff needs to be hidden or fixed
- [ ] cleanup
- [ ] addon got updated in the meantime, check if something broke
