### ISSUE TITLE
CSGN_SP_R3F_ARMES development tracking

### ISSUE THREAD

**Issue by saintblood** [saintblood/CSGN_ServicePack#9]
- [ ] add csgn-magazines
- [ ] hide unpleasant/duplicate weapons
- [ ] adapt existing or create new 25 rounds mags for non-stanag famas
- [ ] translation - this one is important, i understand the dev's did not care, they are french-speaking but 1st im not, 2nd it gets silly as my arma now starts to speak in the 3rd language to me
- [ ] cleanup
